---
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "miniforge3-26.3"
    nodejs: "22"
    rust: "1.91"
  commands:
    - conda env create --quiet --name "${READTHEDOCS_VERSION}" --file environment.yml
    - conda run --no-capture-output --name "${READTHEDOCS_VERSION}" python -m pip install '.[all]'
    - npm ci --ignore-scripts
    - conda run --no-capture-output --name "${READTHEDOCS_VERSION}" python -m dockle check
    - conda run --no-capture-output --name "${READTHEDOCS_VERSION}" python -m dockle build
    - mkdir -p "${READTHEDOCS_OUTPUT}html/"
    - cp -r _site/. "${READTHEDOCS_OUTPUT}html/"

conda:
  environment: environment.yml
