"""Framework adapters and build orchestration."""

from __future__ import annotations

import json
import os
import shlex
import shutil
import subprocess
import sys
from abc import ABC, abstractmethod
from collections.abc import Mapping
from dataclasses import dataclass, field
from html import escape
from pathlib import Path

from dockle import __version__
from dockle.config import DockleConfig, TargetConfig
from dockle.theme import apply_theme, render_theme, write_portal


class BuildError(RuntimeError):
    """Raised when a documentation build cannot complete."""


@dataclass(frozen=True)
class Command:
    """A subprocess invocation without shell interpolation."""

    args: tuple[str, ...]
    cwd: Path
    env: Mapping[str, str] = field(default_factory=dict)

    def display(self) -> str:
        """Return a copyable representation for the current platform."""

        if os.name == "nt":
            return subprocess.list2cmdline(self.args)
        return shlex.join(self.args)


@dataclass(frozen=True)
class BuildPlan:
    """Everything needed to execute one target."""

    target: TargetConfig
    command: Command
    work: Path
    generated_files: Mapping[Path, str]


@dataclass(frozen=True)
class BuildResult:
    """The result of a completed target build."""

    target: TargetConfig
    themed_pages: int


class ProcessRunner:
    """Run adapter commands without invoking a shell."""

    def run(self, command: Command) -> None:
        environment = os.environ.copy()
        environment.update(command.env)
        try:
            completed = subprocess.run(
                command.args,
                cwd=command.cwd,
                env=environment,
                check=False,
            )
        except OSError as error:
            raise BuildError(
                f"could not start {command.args[0]!r}: {error}"
            ) from error
        if completed.returncode:
            raise BuildError(
                f"command failed with exit code {completed.returncode}: {command.display()}"
            )


class Builder(ABC):
    """Base class for a documentation framework adapter."""

    def __init__(
        self, config: DockleConfig, target: TargetConfig, executable: str
    ) -> None:
        self.config = config
        self.target = target
        self.executable = executable
        self.work = config.build.work / target.name

    @abstractmethod
    def plan(self) -> BuildPlan:
        """Create a non-mutating build plan."""

    def finalize(self, stylesheet: str) -> int:
        """Collect framework output and apply the compatibility theme."""

        return apply_theme(
            self.target.output,
            self.target.framework,
            stylesheet,
            portal=self.config.build.output,
            project_name=self.config.project.name,
            project_version=self.config.project.version,
            target_title=self.target.title,
            logo=self.config.project.logo,
        )

    def _theme_file(self) -> Path:
        return self.work / "theme" / "dockle.css"


class SphinxBuilder(Builder):
    """Build Sphinx with Dockle's packaged theme and no consumer ``conf.py``."""

    def _output(self) -> Path:
        """Keep the root site isolated until Sphinx finishes successfully."""

        if self.target.home:
            return self.work / "site"
        return self.target.output

    def plan(self) -> BuildPlan:
        config_file = self.work / "conf.py"
        doctrees = self.work / "doctrees"
        theme_options = {
            "primary": self.config.theme.primary,
            "content": self.config.theme.content,
            "light_background": self.config.theme.light_background,
            "dark_background": self.config.theme.dark_background,
            "font": self.config.theme.font,
            "code_font": self.config.theme.code_font,
            "repository_url": self.config.project.repository,
            "target_title": self.target.title,
            "dockle_version": __version__,
            "dockle_url": "https://github.com/LizardByte/dockle",
        }
        lines = [
            "# Generated by Dockle. Changes will be overwritten.",
            "import sys",
            f"sys.path.insert(0, {str(self.target.source)!r})",
            f"project = {self.config.project.name!r}",
            f"author = {self.config.project.author!r}",
            f"copyright = {self.config.project.copyright!r}",
            f"version = release = {self.config.project.version!r}",
            f"root_doc = {self.target.entry!r}",
            "extensions = [",
            "    'dockle.sphinx_theme',",
            "    'myst_parser',",
            "    'sphinx.ext.autodoc',",
            "]",
            "source_suffix = {'.rst': 'restructuredtext', '.md': 'markdown'}",
            "myst_enable_extensions = ['alert']",
            "html_theme = 'dockle'",
            f"html_theme_options = {theme_options!r}",
            "exclude_patterns = []",
            "",
        ]
        if self.config.project.logo is not None:
            lines.insert(
                -2, f"html_logo = {str(self.config.project.logo)!r}"
            )
        args = [
            self.executable,
            "-b",
            "html",
            "-c",
            str(self.work),
            "-d",
            str(doctrees),
        ]
        if self.config.build.strict:
            args.extend(["-W", "--keep-going"])
        args.extend([str(self.target.source), str(self._output())])
        return BuildPlan(
            target=self.target,
            command=Command(tuple(args), self.config.root),
            work=self.work,
            generated_files={config_file: "\n".join(lines)},
        )

    def finalize(self, stylesheet: str) -> int:
        """Theme and publish an optional root Sphinx site."""

        if not self.target.home:
            return super().finalize(stylesheet)

        staging = self._output()
        themed_pages = apply_theme(
            staging,
            self.target.framework,
            stylesheet,
            portal=None,
            project_name=self.config.project.name,
            project_version=self.config.project.version,
            target_title=self.target.title,
            logo=self.config.project.logo,
        )
        shutil.copytree(staging, self.target.output, dirs_exist_ok=True)
        return themed_pages


class DoxygenBuilder(Builder):
    """Build API documentation from a generated Doxyfile."""

    def plan(self) -> BuildPlan:
        config_file = self.work / "Doxyfile"
        yes_no = "YES" if self.config.build.strict else "NO"
        values = {
            "DOXYFILE_ENCODING": "UTF-8",
            "PROJECT_NAME": _doxygen_quote(self.config.project.name),
            "PROJECT_NUMBER": _doxygen_quote(self.config.project.version),
            "PROJECT_BRIEF": _doxygen_quote(self.config.project.description),
            "OUTPUT_DIRECTORY": _doxygen_quote(_posix(self.target.output)),
            "INPUT": _doxygen_quote(_posix(self.target.source)),
            "RECURSIVE": "YES",
            "GENERATE_HTML": "YES",
            "HTML_OUTPUT": ".",
            "HTML_EXTRA_STYLESHEET": _doxygen_quote(
                _posix(self._theme_file())
            ),
            "GENERATE_TREEVIEW": "YES",
            "FULL_SIDEBAR": "YES",
            "HTML_DYNAMIC_MENUS": "YES",
            "HTML_DYNAMIC_SECTIONS": "YES",
            "SEARCHENGINE": "YES",
            "GENERATE_LATEX": "NO",
            "WARN_AS_ERROR": yes_no,
            "QUIET": "YES",
        }
        entry = self.target.source / self.target.entry
        if entry.is_file():
            values["USE_MDFILE_AS_MAINPAGE"] = _doxygen_quote(_posix(entry))
        dot = shutil.which("dot")
        executable_path = Path(self.executable)
        sibling_dots = (
            executable_path.with_name("dot"),
            executable_path.with_name("dot.exe"),
        )
        if dot:
            values["DOT_PATH"] = _doxygen_quote(_posix(Path(dot).parent))
        else:
            sibling_dot = next(
                (candidate for candidate in sibling_dots if candidate.is_file()),
                None,
            )
            if sibling_dot is not None:
                values["DOT_PATH"] = _doxygen_quote(
                    _posix(sibling_dot.parent)
                )
        aliases = (
            'ALIASES                 = ""\n'
            'ALIASES                += "_dockle_alert{4|}=<dl class=\\"dockle-alert '
            'dockle-alert-\\2\\"><dt class=\\"dockle-alert-title\\"><i data-lucide=\\"\\3\\" '
            'aria-hidden=\\"true\\"></i> \\1</dt><dd>\\4</dd></dl>"\n'
            'ALIASES                += "admonition{2|}=@_dockle_alert{\\1|note|info|\\2}"\n'
            'ALIASES                += "attention{1}=@_dockle_alert{Attention|attention|circle-alert|\\1}"\n'
            'ALIASES                += "caution{1}=@_dockle_alert{Caution|caution|circle-alert|\\1}"\n'
            'ALIASES                += "danger{1}=@_dockle_alert{Danger|danger|octagon-alert|\\1}"\n'
            'ALIASES                += "error{1}=@_dockle_alert{Error|error|circle-x|\\1}"\n'
            'ALIASES                += "hint{1}=@_dockle_alert{Hint|hint|lightbulb|\\1}"\n'
            'ALIASES                += "important{1}=@_dockle_alert{Important|important|flame|\\1}"\n'
            'ALIASES                += "note{1}=@_dockle_alert{Note|note|info|\\1}"\n'
            'ALIASES                += "seealso{1}=@_dockle_alert{See also|seealso|eye|\\1}"\n'
            'ALIASES                += "tip{1}=@_dockle_alert{Tip|tip|lightbulb|\\1}"\n'
            'ALIASES                += "todo{1}=@_dockle_alert{TODO|todo|list-todo|\\1}"\n'
            'ALIASES                += "warning{1}=@_dockle_alert{Warning|warning|triangle-alert|\\1}"\n'
        )
        contents = (
            "# Generated by Dockle. Changes will be overwritten.\n"
            + "".join(
                f"{key:<24} = {value}\n" for key, value in values.items()
            )
            + aliases
        )
        return BuildPlan(
            target=self.target,
            command=Command(
                (self.executable, str(config_file)), self.config.root
            ),
            work=self.work,
            generated_files={
                config_file: contents,
                self._theme_file(): render_theme(self.config.theme),
            },
        )


class MkDocsBuilder(Builder):
    """Build Markdown with a generated MkDocs configuration."""

    def plan(self) -> BuildPlan:
        config_file = self.work / "mkdocs.yml"
        lines = [
            "# Generated by Dockle. Changes will be overwritten.",
            f"site_name: {_yaml_string(self.config.project.name)}",
            f"site_description: {_yaml_string(self.config.project.description)}",
            f"site_author: {_yaml_string(self.config.project.author)}",
            f"copyright: {_yaml_string(self.config.project.copyright)}",
            f"docs_dir: {_yaml_string(str(self.target.source))}",
            f"site_dir: {_yaml_string(str(self.target.output))}",
            'edit_uri: ""',
            "theme:",
            "  name: dockle",
            f"  primary: {_yaml_string(self.config.theme.primary)}",
            f"  content: {_yaml_string(self.config.theme.content)}",
            f"  light_background: {_yaml_string(self.config.theme.light_background)}",
            f"  dark_background: {_yaml_string(self.config.theme.dark_background)}",
            f"  font: {_yaml_string(self.config.theme.font)}",
            f"  code_font: {_yaml_string(self.config.theme.code_font)}",
            f"  version: {_yaml_string(self.config.project.version)}",
            f"  target_title: {_yaml_string(self.target.title)}",
            f"  dockle_version: {_yaml_string(__version__)}",
            '  dockle_url: "https://github.com/LizardByte/dockle"',
            "markdown_extensions:",
            "  - admonition",
            "  - dockle.markdown",
        ]
        if self.config.project.repository:
            lines.append(
                f"repo_url: {_yaml_string(self.config.project.repository)}"
            )
        args = [self.executable, "build", "--config-file", str(config_file)]
        if self.config.build.strict:
            args.append("--strict")
        return BuildPlan(
            target=self.target,
            command=Command(tuple(args), self.config.root),
            work=self.work,
            generated_files={config_file: "\n".join(lines) + "\n"},
        )


class JsDocBuilder(Builder):
    """Build JavaScript API documentation from generated JSON."""

    def plan(self) -> BuildPlan:
        config_file = self.work / "jsdoc.json"
        native = {
            "source": {
                "include": [str(self.target.source)],
                "includePattern": r".+\.(c|m)?jsx?$",
            },
            "opts": {
                "destination": str(self.target.output),
                "encoding": "utf8",
                "recurse": True,
            },
            "templates": {
                "default": {"includeDate": False, "outputSourceFiles": True}
            },
        }
        entry = self.target.source / self.target.entry
        if entry.is_file():
            native["opts"]["readme"] = str(entry)
        tutorials = self.target.source / "tutorials"
        if tutorials.is_dir():
            native["opts"]["tutorials"] = str(tutorials)
        args = [self.executable, "--configure", str(config_file)]
        if self.config.build.strict:
            args.append("--pedantic")
        return BuildPlan(
            target=self.target,
            command=Command(tuple(args), self.config.root),
            work=self.work,
            generated_files={config_file: json.dumps(native, indent=2) + "\n"},
        )


class RustdocBuilder(Builder):
    """Build a Cargo package or workspace with rustdoc."""

    def plan(self) -> BuildPlan:
        manifest = self.target.source
        if manifest.is_dir():
            manifest /= "Cargo.toml"
        cargo_target = self.work / "cargo-target"
        args = [
            self.executable,
            "doc",
            "--manifest-path",
            str(manifest),
            "--target-dir",
            str(cargo_target),
            "--no-deps",
        ]
        env: dict[str, str] = {}
        if self.config.build.strict:
            existing_flags = os.environ.get("RUSTDOCFLAGS", "")
            env["RUSTDOCFLAGS"] = f"{existing_flags} -D warnings".strip()
        return BuildPlan(
            target=self.target,
            command=Command(tuple(args), self.config.root, env),
            work=self.work,
            generated_files={},
        )

    def finalize(self, stylesheet: str) -> int:
        source = self.work / "cargo-target" / "doc"
        if not source.is_dir():
            raise BuildError(
                f"cargo did not generate rustdoc output in {source}"
            )
        shutil.copytree(source, self.target.output, dirs_exist_ok=True)
        self._write_index()
        return super().finalize(stylesheet)

    def _write_index(self) -> None:
        """Create the root page that Cargo omits for package documentation."""

        crates = sorted(
            path
            for path in self.target.output.iterdir()
            if path.is_dir() and (path / "index.html").is_file()
        )
        if not crates:
            raise BuildError(
                f"cargo did not generate a crate index in {self.target.output}"
            )

        if len(crates) == 1:
            destination = f"{crates[0].name}/"
            script_destination = json.dumps(destination)
            head_extra = (
                '<meta http-equiv="refresh" content="0; '
                f'url={escape(destination)}">\n'
                "  <script>window.location.replace("
                f"{script_destination});</script>"
            )
            body = f'  <p>Continue to <a href="{escape(destination)}">{escape(crates[0].name)}</a>.</p>'
        else:
            head_extra = ""
            links = "\n".join(
                f'    <li><a href="{escape(crate.name)}/">{escape(crate.name)}</a></li>'
                for crate in crates
            )
            body = f"  <h1>{escape(self.target.title)}</h1>\n  <ul>\n{links}\n  </ul>"

        document = f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{escape(self.target.title)}</title>
  {head_extra}
</head>
<body>
  <main>
{body}
  </main>
</body>
</html>
"""
        (self.target.output / "index.html").write_text(
            document, encoding="utf-8"
        )


_BUILDERS: dict[str, type[Builder]] = {
    "doxygen": DoxygenBuilder,
    "jsdoc": JsDocBuilder,
    "mkdocs": MkDocsBuilder,
    "rustdoc": RustdocBuilder,
    "sphinx": SphinxBuilder,
}


class BuildManager:
    """Resolve tools and execute one or more framework adapters."""

    def __init__(
        self, config: DockleConfig, runner: ProcessRunner | None = None
    ) -> None:
        self.config = config
        self.runner = runner or ProcessRunner()

    def plan(
        self, target: TargetConfig, *, require_tool: bool = False
    ) -> BuildPlan:
        """Create a target plan, optionally requiring its executable."""

        executable = self._resolve_tool(
            target.framework, required=require_tool
        )
        builder = _BUILDERS[target.framework](self.config, target, executable)
        return builder.plan()

    def check(
        self, targets: tuple[TargetConfig, ...]
    ) -> list[tuple[TargetConfig, str | None]]:
        """Check source paths and tool availability without writing files."""

        checks: list[tuple[TargetConfig, str | None]] = []
        for target in targets:
            problem: str | None = None
            if not target.source.exists():
                problem = f"source does not exist: {target.source}"
            else:
                try:
                    self._resolve_tool(target.framework, required=True)
                except BuildError as error:
                    problem = str(error)
            checks.append((target, problem))
        return checks

    def build(
        self, targets: tuple[TargetConfig, ...]
    ) -> tuple[BuildResult, ...]:
        """Build selected targets in configuration order."""

        results: list[BuildResult] = []
        stylesheet = render_theme(self.config.theme)
        if self.config.build.clean and targets == self.config.targets:
            self._prepare_directory(self.config.build.output, clean=True)
        for target in targets:
            if not target.source.exists():
                raise BuildError(
                    f"source does not exist for target {target.name!r}: {target.source}"
                )
            executable = self._resolve_tool(target.framework, required=True)
            builder = _BUILDERS[target.framework](
                self.config, target, executable
            )
            plan = builder.plan()
            self._prepare_directory(plan.work, clean=True)
            if not target.home:
                self._prepare_directory(
                    target.output, clean=self.config.build.clean
                )
            for path, contents in plan.generated_files.items():
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(contents, encoding="utf-8")
            self.runner.run(plan.command)
            themed_pages = builder.finalize(stylesheet)
            results.append(
                BuildResult(target=target, themed_pages=themed_pages)
            )
        write_portal(self.config, targets, stylesheet)
        return tuple(results)

    def _resolve_tool(self, framework: str, *, required: bool) -> str:
        configured = self.config.tool(framework)
        candidate = Path(configured)
        resolved: str | None
        if candidate.is_absolute() or "/" in configured or "\\" in configured:
            local = (
                candidate
                if candidate.is_absolute()
                else self.config.root / candidate
            )
            resolved = str(local.resolve()) if local.exists() else None
        else:
            interpreter_scripts = str(Path(sys.executable).resolve().parent)
            local_node_modules = str(
                self.config.root / "node_modules" / ".bin"
            )
            resolved = (
                shutil.which(configured, path=interpreter_scripts)
                or shutil.which(configured, path=local_node_modules)
                or shutil.which(configured)
            )
        if resolved:
            return resolved
        if required:
            raise BuildError(
                f"tool for {framework!r} was not found: {configured!r}; "
                f"install it or set tools.{framework} in {self.config.path.name}"
            )
        return configured

    def _prepare_directory(self, path: Path, *, clean: bool) -> None:
        root = self.config.root.resolve()
        resolved = path.resolve()
        if resolved == root or not resolved.is_relative_to(root):
            raise BuildError(
                f"refusing to prepare unsafe directory: {resolved}"
            )
        if clean and resolved.exists():
            shutil.rmtree(resolved)
        resolved.mkdir(parents=True, exist_ok=True)


def _doxygen_quote(value: str) -> str:
    escaped = value.replace('"', '\\"')
    return f'"{escaped}"'


def _posix(path: Path) -> str:
    return path.as_posix()


def _yaml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)
