"""Generate and apply Dockle's framework-neutral theme."""

from __future__ import annotations

import json
import os
import re
import shutil
from html import escape
from html.parser import HTMLParser
from importlib.metadata import PackageNotFoundError, version
from pathlib import Path

from dockle import __version__
from dockle.config import DockleConfig, TargetConfig, ThemeConfig
from dockle.markdown import render_markdown

_HEAD_END = re.compile(r"</head\s*>", re.IGNORECASE)
_HTML_START = re.compile(r"<html(?P<attributes>\s[^>]*)?>", re.IGNORECASE)
_BODY_START = re.compile(r"<body(?P<attributes>\s[^>]*)?>", re.IGNORECASE)
_BODY_END = re.compile(r"</body\s*>", re.IGNORECASE)
_JSDOC_HOME_TITLE = re.compile(
    r'<h1\s+class=["\']page-title["\']>\s*Home\s*</h1>',
    re.IGNORECASE,
)
_JSDOC_GENERATOR_FOOTER_START = re.compile(
    r"<footer\b(?![^>]*data-dockle-built-with)[^>]*>\s*"
    r"Documentation generated by",
    re.IGNORECASE,
)
_DOXYGEN_GENERATOR_ITEM_START = re.compile(
    r'<li\s+class=["\']footer["\'][^>]*>\s*Generated by',
    re.IGNORECASE,
)
_DOCKLE_FOOTER_START = re.compile(
    r"<footer\b(?=[^>]*data-dockle-built-with)[^>]*>",
    re.IGNORECASE,
)
_TARGET_CARDS_START = re.compile(
    r'<div\s+data-dockle-target-cards(?:=["\'][^"\']*["\'])?[^>]*>',
    re.IGNORECASE,
)
_FIRST_H1_END = re.compile(r"</h1\s*>", re.IGNORECASE)
_DOXYGEN_FRAGMENT = re.compile(
    r'(?P<open><div\s+class=["\'][^"\']*\bfragment\b[^"\']*["\'][^>]*>)'
    r"(?P<body>.*?)"
    r"(?P<close></div><!--\s*fragment\s*-->)",
    re.IGNORECASE | re.DOTALL,
)
_DOXYGEN_FRAGMENT_LINE = re.compile(
    r'<div\s+class=["\'][^"\']*\bline\b[^"\']*["\'][^>]*>'
    r"(?P<body>.*?)</div>",
    re.IGNORECASE | re.DOTALL,
)
_MARKDOWN_FENCE = re.compile(
    r"^(?P<indent> {0,3})(?P<fence>`{3,}|~{3,})(?P<info>.*)$"
)
_DOCKLE_URL = "https://github.com/LizardByte/dockle"
_CSS_ASSET = "dockle.css"
_SCRIPT_ASSET = "dockle.js"
_LUCIDE_ASSET = "lucide.min.js"
_HIGHLIGHT_ASSET = "highlight.min.js"
_INDEX_FILE = "index.html"
_FRAMEWORKS = {
    "doxygen": ("Doxygen", "https://www.doxygen.nl/"),
    "jsdoc": ("JSDoc", "https://jsdoc.app/"),
    "mkdocs": ("MkDocs", "https://www.mkdocs.org/"),
    "rustdoc": ("rustdoc", "https://doc.rust-lang.org/rustdoc/"),
    "sphinx": ("Sphinx", "https://www.sphinx-doc.org/"),
}
_FRAMEWORK_VERSION_PATTERNS = {
    "doxygen": re.compile(
        r'<meta\s+name=["\']generator["\']\s+content=["\']Doxygen\s+([^"\']+)',
        re.IGNORECASE,
    ),
    "rustdoc": re.compile(
        r'data-channel=["\']([^"\']+)',
        re.IGNORECASE,
    ),
}
_FRAMEWORK_DISTRIBUTIONS = {"mkdocs": "mkdocs", "sphinx": "Sphinx"}


class ThemeError(RuntimeError):
    """Raised when generated HTML cannot be themed safely."""


class _SearchDocumentParser(HTMLParser):
    """Collect useful searchable text from one generated HTML page."""

    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.title: list[str] = []
        self.text: list[str] = []
        self._in_title = False
        self._ignored = 0

    def handle_starttag(
        self,
        tag: str,
        attrs: list[tuple[str, str | None]],
    ) -> None:
        del attrs
        if tag in {"script", "style", "svg"}:
            self._ignored += 1
        if tag == "title":
            self._in_title = True

    def handle_endtag(self, tag: str) -> None:
        if tag == "title":
            self._in_title = False
        if tag in {"script", "style", "svg"} and self._ignored:
            self._ignored -= 1

    def handle_data(self, data: str) -> None:
        if self._ignored:
            return
        cleaned = " ".join(data.split())
        if not cleaned:
            return
        self.text.append(cleaned)
        if self._in_title:
            self.title.append(cleaned)


class _LinkRelationshipParser(HTMLParser):
    """Identify icon relationships on one link element."""

    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.has_icon_relationship = False

    def handle_starttag(
        self,
        tag: str,
        attrs: list[tuple[str, str | None]],
    ) -> None:
        if tag != "link":
            return
        relationship = next(
            (value for name, value in attrs if name == "rel"),
            None,
        )
        if relationship is not None:
            self.has_icon_relationship = any(
                "icon" in token.casefold() for token in relationship.split()
            )


class _TextContentParser(HTMLParser):
    """Extract decoded text from a generated HTML fragment."""

    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.parts: list[str] = []

    def handle_data(self, data: str) -> None:
        self.parts.append(data)


def _theme_asset(name: str) -> Path:
    return (
        Path(__file__)
        .with_name("sphinx")
        .joinpath("themes", "dockle", "static", name)
    )


def render_theme(theme: ThemeConfig) -> str:
    """Combine the base stylesheet with configured design tokens."""

    base = _theme_asset(_CSS_ASSET).read_text(encoding="utf-8")
    tokens = f"""/* Generated from dockle.toml. */
:root,
:root[data-color-scheme="light"] {{
  --dockle-primary: {theme.primary};
  --dockle-content: {theme.content};
  --dockle-background: {theme.light_background};
  --dockle-font: {theme.font};
  --dockle-code-font: {theme.code_font};
}}

:root[data-color-scheme="dark"] {{
  --dockle-content: #e5e7eb;
  --dockle-background: {theme.dark_background};
}}

@media (prefers-color-scheme: dark) {{
  :root:not([data-color-scheme]) {{
    --dockle-content: #e5e7eb;
    --dockle-background: {theme.dark_background};
  }}
}}
"""
    return f"{tokens}\n{base}"


def annotate_doxygen_code_languages(output: Path, source: Path) -> int:
    """Restore Markdown fence languages that Doxygen drops from its HTML."""

    languages = _fenced_code_languages(source)
    if not languages:
        return 0

    annotated = 0
    for html_file in sorted(output.rglob("*.html")):
        document = html_file.read_text(encoding="utf-8")

        def annotate(match: re.Match[str]) -> str:
            nonlocal annotated
            opening = match.group("open")
            if "data-dockle-language" in opening:
                return match.group(0)
            body = match.group("body")
            code = _doxygen_fragment_text(body)
            candidates = languages.get(_normalized_code(code), set())
            if not candidates:
                lines = _DOXYGEN_FRAGMENT_LINE.findall(body)
                if lines:
                    parser = _TextContentParser()
                    parser.feed(lines[0])
                    echoed_language = "".join(parser.parts).strip().casefold()
                    body_without_info = _DOXYGEN_FRAGMENT_LINE.sub(
                        "", body, count=1
                    )
                    code_without_info = _doxygen_fragment_text(
                        body_without_info
                    )
                    possible = languages.get(
                        _normalized_code(code_without_info), set()
                    )
                    if (
                        echoed_language
                        and len(possible) == 1
                        and next(iter(possible)).endswith(echoed_language)
                    ):
                        candidates = possible
                        body = body_without_info
            if len(candidates) != 1:
                return match.group(0)
            language = next(iter(candidates))
            marked = f'{opening[:-1]} data-dockle-language="{escape(language)}">'
            annotated += 1
            return f'{marked}{body}{match.group("close")}'

        updated = _DOXYGEN_FRAGMENT.sub(annotate, document)
        if updated != document:
            html_file.write_text(updated, encoding="utf-8")
    return annotated


def _fenced_code_languages(source: Path) -> dict[str, set[str]]:
    languages: dict[str, set[str]] = {}
    markdown_files = (
        [source]
        if source.is_file() and source.suffix.casefold() == ".md"
        else sorted(source.rglob("*.md"))
    )
    for markdown_file in markdown_files:
        lines = markdown_file.read_text(encoding="utf-8").splitlines()
        index = 0
        while index < len(lines):
            opening = _MARKDOWN_FENCE.match(lines[index])
            if opening is None:
                index += 1
                continue
            fence = opening.group("fence")
            language = _fence_language(opening.group("info"))
            closing = re.compile(
                rf"^ {{0,3}}{re.escape(fence[0])}{{{len(fence)},}}[ \t]*$"
            )
            block: list[str] = []
            index += 1
            while index < len(lines) and closing.match(lines[index]) is None:
                block.append(lines[index])
                index += 1
            if language and block:
                key = _normalized_code("\n".join(block))
                languages.setdefault(key, set()).add(language)
            index += 1
    return languages


def _fence_language(info: str) -> str:
    token = info.strip().split(maxsplit=1)[0] if info.strip() else ""
    return token.strip("{}").removeprefix(".").casefold()


def _doxygen_fragment_text(fragment: str) -> str:
    lines: list[str] = []
    for match in _DOXYGEN_FRAGMENT_LINE.finditer(fragment):
        parser = _TextContentParser()
        parser.feed(match.group("body"))
        lines.append("".join(parser.parts))
    return "\n".join(lines)


def _normalized_code(code: str) -> str:
    return "\n".join(line.rstrip() for line in code.splitlines()).strip("\n")


def apply_theme(
    output: Path,
    framework: str,
    stylesheet: str,
    *,
    portal: Path | None = None,
    project_name: str = "",
    project_version: str = "",
    target_title: str = "",
    logo: Path | None = None,
    favicon: Path | None = None,
) -> int:
    """Inject shared assets, navigation, branding, and client search."""

    html_files = sorted(output.rglob("*.html"))
    if not html_files:
        raise ThemeError(
            f"{framework} did not generate any HTML files in {output}"
        )

    asset_dir = _write_theme_assets(output, stylesheet)
    logo_asset = _copy_logo(logo, asset_dir)
    favicon_asset = _copy_favicon(favicon, asset_dir)
    search_documents = _build_search_documents(html_files, output)
    (asset_dir / "search.json").write_text(
        json.dumps({"docs": search_documents}, ensure_ascii=False),
        encoding="utf-8",
    )

    native_theme = framework in {"sphinx", "doxygen", "mkdocs"}
    framework_version = _framework_version(framework, html_files)
    footer = _built_with_footer(framework, framework_version)
    themed = 0
    for html_file in html_files:
        document = html_file.read_text(encoding="utf-8")
        original = document
        document = _remove_framework_generator(
            document, framework, html_file == output / _INDEX_FILE
        )
        document = _inject_theme_assets(
            document, html_file, asset_dir, framework, native_theme
        )
        document = _inject_favicon(document, html_file, favicon_asset)
        document = _mark_framework(document, html_file, framework)

        decorations = _page_decorations(
            html_file=html_file,
            output=output,
            portal=portal,
            framework=framework,
            project_name=project_name,
            project_version=project_version,
            target_title=target_title,
            logo_asset=logo_asset,
            include_theme_toggle=(
                "data-dockle-theme-toggle" not in document
            ),
        )
        if "data-dockle-universal-search" not in document:
            document = _insert_after_body(document, decorations, html_file)
        document = _ensure_footer(document, footer, html_file)

        if document != original:
            html_file.write_text(document, encoding="utf-8")
            themed += 1
    return themed


def _write_theme_assets(output: Path, stylesheet: str) -> Path:
    asset_dir = output / "_dockle"
    asset_dir.mkdir(parents=True, exist_ok=True)
    (asset_dir / _CSS_ASSET).write_text(stylesheet, encoding="utf-8")
    for asset in (_LUCIDE_ASSET, _HIGHLIGHT_ASSET, _SCRIPT_ASSET):
        shutil.copyfile(_theme_asset(asset), asset_dir / asset)
    return asset_dir


def _remove_framework_generator(
    document: str, framework: str, is_index: bool
) -> str:
    if framework == "jsdoc" and is_index:
        document = _JSDOC_HOME_TITLE.sub("", document, count=1)
    if framework == "jsdoc":
        document, _ = _replace_element(
            document, _JSDOC_GENERATOR_FOOTER_START, "</footer>", ""
        )
    if framework == "doxygen":
        document, _ = _replace_element(
            document, _DOXYGEN_GENERATOR_ITEM_START, "</li>", ""
        )
    return document


def _inject_theme_assets(
    document: str,
    html_file: Path,
    asset_dir: Path,
    framework: str,
    native_theme: bool,
) -> str:
    if not native_theme and "data-dockle-theme" not in document:
        relative_css = _relative(asset_dir / _CSS_ASSET, html_file)
        link = (
            f'<link rel="stylesheet" href="{relative_css}" '
            f'data-dockle-theme="{framework}">\n'
        )
        document = _insert_before_head_end(document, link, html_file)
    if _LUCIDE_ASSET not in document:
        relative_lucide = _relative(asset_dir / _LUCIDE_ASSET, html_file)
        script = (
            f'<script defer src="{relative_lucide}" '
            "data-dockle-lucide></script>\n"
        )
        document = _insert_before_head_end(document, script, html_file)
    if _HIGHLIGHT_ASSET not in document:
        relative_highlight = _relative(
            asset_dir / _HIGHLIGHT_ASSET, html_file
        )
        script = (
            f'<script defer src="{relative_highlight}" '
            "data-dockle-highlight></script>\n"
        )
        document = _insert_before_head_end(document, script, html_file)
    if _SCRIPT_ASSET not in document:
        relative_script = _relative(asset_dir / _SCRIPT_ASSET, html_file)
        script = (
            f'<script defer src="{relative_script}" '
            "data-dockle-script></script>\n"
        )
        document = _insert_before_head_end(document, script, html_file)
    return document


def _mark_framework(document: str, html_file: Path, framework: str) -> str:
    if "data-dockle-framework" in document:
        return document
    html_start = _HTML_START.search(document)
    if html_start is None:
        raise ThemeError(f"generated HTML has no root html element: {html_file}")
    attributes = html_start.group("attributes") or ""
    themed_root = f'<html data-dockle-framework="{framework}"{attributes}>'
    return (
        f"{document[:html_start.start()]}{themed_root}"
        f"{document[html_start.end():]}"
    )


def _ensure_footer(document: str, footer: str, html_file: Path) -> str:
    if "data-dockle-built-with" not in document:
        return _insert_before_body_end(document, footer, html_file)
    updated, replacements = _replace_element(
        document, _DOCKLE_FOOTER_START, "</footer>", footer, count=1
    )
    return updated if replacements else document


def _replace_element(
    document: str,
    start_pattern: re.Pattern[str],
    closing_tag: str,
    replacement: str,
    *,
    count: int = 0,
) -> tuple[str, int]:
    replacements = 0
    offset = 0
    closing_lower = closing_tag.lower()
    while not count or replacements < count:
        match = start_pattern.search(document, offset)
        if match is None:
            break
        closing = document.lower().find(closing_lower, match.end())
        if closing < 0:
            break
        end = closing + len(closing_tag)
        document = f"{document[:match.start()]}{replacement}{document[end:]}"
        offset = match.start() + len(replacement)
        replacements += 1
    return document, replacements


def _insert_before_head_end(
    document: str,
    markup: str,
    html_file: Path,
) -> str:
    match = _HEAD_END.search(document)
    if match is None:
        raise ThemeError(
            f"generated HTML has no closing head element: {html_file}"
        )
    return f"{document[:match.start()]}{markup}{document[match.start():]}"


def _insert_after_body(
    document: str,
    markup: str,
    html_file: Path,
) -> str:
    match = _BODY_START.search(document)
    if match is None:
        raise ThemeError(f"generated HTML has no body element: {html_file}")
    return f"{document[:match.end()]}{markup}{document[match.end():]}"


def _insert_before_body_end(
    document: str,
    markup: str,
    html_file: Path,
) -> str:
    match = _BODY_END.search(document)
    if match is None:
        raise ThemeError(f"generated HTML has no closing body element: {html_file}")
    return f"{document[:match.start()]}{markup}{document[match.start():]}"


def _relative(asset: Path, html_file: Path) -> str:
    return Path(os.path.relpath(asset, html_file.parent)).as_posix()


def _copy_logo(logo: Path | None, asset_dir: Path) -> Path | None:
    if logo is None:
        return None
    destination = asset_dir / f"logo{logo.suffix.lower()}"
    shutil.copyfile(logo, destination)
    return destination


def _copy_favicon(favicon: Path | None, asset_dir: Path) -> Path | None:
    if favicon is None:
        return None
    destination = asset_dir / f"favicon{favicon.suffix.lower()}"
    shutil.copyfile(favicon, destination)
    return destination


def _inject_favicon(
    document: str,
    html_file: Path,
    favicon_asset: Path | None,
) -> str:
    if favicon_asset is None:
        return document
    document = _remove_favicon_links(document)
    relative_favicon = _relative(favicon_asset, html_file)
    link = (
        f'<link rel="icon" href="{relative_favicon}" '
        "data-dockle-favicon>\n"
    )
    return _insert_before_head_end(document, link, html_file)


def _remove_favicon_links(document: str) -> str:
    """Remove existing icon link elements without regex backtracking."""

    folded = document.casefold()
    fragments: list[str] = []
    retained_from = 0
    search_from = 0
    while (start := folded.find("<link", search_from)) >= 0:
        name_end = start + len("<link")
        if name_end < len(document) and document[name_end] not in " />\t\r\n":
            search_from = name_end
            continue
        end = _find_tag_end(document, name_end)
        if end is None:
            break
        tag = document[start:end + 1]
        parser = _LinkRelationshipParser()
        parser.feed(tag)
        search_from = end + 1
        if not parser.has_icon_relationship:
            continue
        while search_from < len(document) and document[search_from].isspace():
            search_from += 1
        fragments.append(document[retained_from:start])
        retained_from = search_from
    fragments.append(document[retained_from:])
    return "".join(fragments)


def _find_tag_end(document: str, start: int) -> int | None:
    """Find a tag terminator while respecting quoted attribute values."""

    quote: str | None = None
    for index in range(start, len(document)):
        character = document[index]
        if quote is not None:
            if character == quote:
                quote = None
            continue
        if character in {'"', "'"}:
            quote = character
        elif character == ">":
            return index
    return None


def _build_search_documents(
    html_files: list[Path],
    output: Path,
) -> list[dict[str, str]]:
    documents: list[dict[str, str]] = []
    for html_file in html_files:
        parser = _SearchDocumentParser()
        parser.feed(html_file.read_text(encoding="utf-8"))
        text = " ".join(parser.text)
        title = " ".join(parser.title)
        if not title:
            title = html_file.stem.replace("-", " ").title()
        documents.append(
            {
                "location": html_file.relative_to(output).as_posix(),
                "title": title,
                "text": text[:4000],
            }
        )
    return documents


def _page_decorations(
    *,
    html_file: Path,
    output: Path,
    portal: Path | None,
    framework: str,
    project_name: str,
    project_version: str,
    target_title: str,
    logo_asset: Path | None,
    include_theme_toggle: bool,
) -> str:
    relative_index = _relative(
        output / "_dockle" / "search.json",
        html_file,
    )
    relative_root = _relative(output, html_file)
    logo_url = _relative(logo_asset, html_file) if logo_asset else ""
    search = f"""<div class="dockle-search dockle-universal-search"
       data-dockle-universal-search data-dockle-logo-url="{logo_url}"
       data-dockle-target-title="{escape(target_title)}">
    <i class="dockle-search-icon" data-lucide="search" aria-hidden="true"></i>
    <label class="visually-hidden" for="dockle-search-input">
      Search documentation
    </label>
    <input id="dockle-search-input" type="search"
           placeholder="Search documentation" autocomplete="off"
           data-dockle-search="{relative_index}"
           data-dockle-root="{relative_root}">
    <ul class="dockle-search-results"
        data-dockle-search-results="dockle-search-input"
        aria-live="polite" hidden></ul>
  </div>"""
    links = ""
    if portal is not None:
        relative_portal = _relative(portal / _INDEX_FILE, html_file)
        links += (
            f'<a class="dockle-home" href="{relative_portal}" '
            'data-dockle-home><i data-lucide="arrow-left" '
            'aria-hidden="true"></i>All docs</a>'
        )
    if (
        portal is not None
        and project_name
        and framework in {"doxygen", "jsdoc", "rustdoc"}
    ):
        relative_portal = _relative(portal / _INDEX_FILE, html_file)
        version = (
            f"<span>{escape(project_version)}</span>"
            if project_version
            else ""
        )
        links += (
            f'<a class="dockle-compat-brand" href="{relative_portal}" '
            f"data-dockle-brand><strong>{escape(project_name)}</strong>"
            f"{version}</a>"
        )
    toggle = ""
    if include_theme_toggle:
        toggle = (
            '<button type="button" class="dockle-theme-toggle" '
            'data-dockle-theme-toggle aria-label="Color scheme: auto">'
            '<i data-lucide="monitor" aria-hidden="true"></i></button>'
        )
    return f'{links}<div class="dockle-toolbar">{search}{toggle}</div>'


def _framework_version(framework: str, html_files: list[Path]) -> str:
    if framework == "jsdoc":
        jsdoc_version = _jsdoc_version(html_files)
        if jsdoc_version:
            return jsdoc_version
    pattern = _FRAMEWORK_VERSION_PATTERNS.get(framework)
    if pattern is not None:
        for html_file in html_files:
            match = pattern.search(html_file.read_text(encoding="utf-8"))
            if match is not None:
                return match.group(1).strip()
    distribution = _FRAMEWORK_DISTRIBUTIONS.get(framework)
    if distribution is None:
        return ""
    try:
        return version(distribution)
    except PackageNotFoundError:
        return ""


def _jsdoc_version(html_files: list[Path]) -> str:
    marker = "jsdoc "
    closing_tag = "</a>"
    for html_file in html_files:
        document = html_file.read_text(encoding="utf-8")
        lowered = document.lower()
        start = lowered.find(marker)
        if start < 0:
            continue
        start += len(marker)
        end = lowered.find(closing_tag, start)
        if end >= 0:
            return document[start:end].strip()
    return ""


def _built_with_footer(framework: str = "", framework_version: str = "") -> str:
    framework_name, framework_url = _FRAMEWORKS.get(
        framework,
        (framework, ""),
    )
    framework_attribution = ""
    if framework_name:
        label = escape(framework_name)
        if framework_version:
            label += f" {escape(framework_version)}"
        if framework_url:
            label = (
                f'<a href="{framework_url}">{label}'
                '<i data-lucide="external-link" aria-hidden="true"></i></a>'
            )
        framework_attribution = f" with {label}"
    return (
        '<footer class="dockle-footer dockle-built-with" '
        'data-dockle-built-with>'
        f'Generated by <a href="{_DOCKLE_URL}">Dockle {__version__}'
        '<i data-lucide="external-link" aria-hidden="true"></i>'
        f'</a>{framework_attribution}.</footer>'
    )


def write_portal(
    config: DockleConfig,
    targets: tuple[TargetConfig, ...],
    stylesheet: str,
) -> Path:
    """Write the root project documentation and comparison cards."""

    output = config.build.output
    output.mkdir(parents=True, exist_ok=True)
    home_target = next((target for target in config.targets if target.home), None)
    card_targets = (
        tuple(target for target in config.targets if not target.home)
        if home_target is not None
        else targets
    )
    cards = _portal_cards(card_targets, output)
    portal = output / _INDEX_FILE
    if home_target is not None and portal.is_file():
        document = portal.read_text(encoding="utf-8")
        cards_markup = (
            '<div data-dockle-target-cards class="dockle-portal-grid" '
            'aria-label="Documentation examples">\n'
            f"{cards}\n"
            "</div>"
        )
        document, replacements = _replace_element(
            document,
            _TARGET_CARDS_START,
            "</div>",
            cards_markup,
            count=1,
        )
        if not replacements:
            heading = _FIRST_H1_END.search(document)
            if heading is None:
                raise ThemeError(
                    f"home target has no heading for comparison cards: {portal}"
                )
            document = (
                f"{document[:heading.end()]}\n{cards_markup}"
                f"{document[heading.end():]}"
            )
        portal.write_text(document, encoding="utf-8")
        return portal

    asset_dir = _write_theme_assets(output, stylesheet)
    logo_asset = _copy_logo(config.project.logo, asset_dir)
    favicon_asset = _copy_favicon(config.project.favicon, asset_dir)

    version = (
        f" <span>{escape(config.project.version)}</span>"
        if config.project.version
        else ""
    )
    repository = ""
    if config.project.repository:
        repository = (
            '    <p class="dockle-portal-repository">'
            f'<a href="{escape(config.project.repository)}">'
            'Source repository<i data-lucide="external-link" '
            'aria-hidden="true"></i></a></p>\n'
        )
    logo = ""
    if logo_asset is not None:
        logo = (
            f'      <img class="dockle-portal-logo" '
            f'src="_dockle/{escape(logo_asset.name)}" alt="">\n'
        )
    favicon = ""
    if favicon_asset is not None:
        favicon = (
            f'  <link rel="icon" href="_dockle/{escape(favicon_asset.name)}" '
            "data-dockle-favicon>\n"
        )
    project_docs = ""
    if config.project.home is not None:
        source = config.project.home.read_text(encoding="utf-8")
        project_docs = (
            '    <article class="dockle-portal-docs">\n'
            f"{render_markdown(source)}\n"
            "    </article>\n"
        )

    document = f"""<!doctype html>
<html lang="en" data-dockle-framework="portal">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="{escape(config.project.description)}">
  <title>{escape(config.project.name)} documentation</title>
{favicon}  <link rel="stylesheet" href="_dockle/dockle.css" data-dockle-theme="portal">
  <script defer src="_dockle/lucide.min.js" data-dockle-lucide></script>
  <script defer src="_dockle/highlight.min.js" data-dockle-highlight></script>
  <script defer src="_dockle/dockle.js" data-dockle-script></script>
</head>
<body class="dockle-portal">
  <main>
    <header>
{logo}      <div>
        <p class="dockle-portal-kicker">Documentation</p>
        <h1>{escape(config.project.name)}{version}</h1>
        <p>{escape(config.project.description)}</p>
      </div>
    </header>
    <section class="dockle-portal-grid" aria-label="Documentation examples">
{cards}
    </section>
{project_docs}{repository}  </main>
  <footer class="dockle-footer dockle-built-with dockle-portal-built-with"
          data-dockle-built-with>
    Generated by <a href="{_DOCKLE_URL}">Dockle {__version__}<i
      data-lucide="external-link" aria-hidden="true"></i></a>.
  </footer>
  <button type="button" class="dockle-theme-toggle"
          data-dockle-theme-toggle aria-label="Color scheme: auto">
    <i data-lucide="monitor" aria-hidden="true"></i>
  </button>
</body>
</html>
"""
    portal.write_text(document, encoding="utf-8")
    return portal


def _portal_cards(
    targets: tuple[TargetConfig, ...], output: Path
) -> str:
    """Render the shared comparison cards for portal or Sphinx home pages."""

    cards: list[str] = []
    for target in targets:
        relative = _target_href(target, output)
        description = target.description or (
            f"Documentation generated with {target.framework}."
        )
        cards.append(
            f"""      <a class="dockle-portal-card" href="{escape(relative)}">
        <span class="dockle-portal-framework">{escape(target.framework)}</span>
        <strong>{escape(target.title)}</strong>
        <span>{escape(description)}</span>
      </a>"""
        )
    return "\n".join(cards)


def _target_href(target: TargetConfig, output: Path) -> str:
    relative = target.output.relative_to(output).as_posix()
    if target.framework == "rustdoc" and target.output.is_dir():
        crates = sorted(
            path
            for path in target.output.iterdir()
            if path.is_dir() and (path / _INDEX_FILE).is_file()
        )
        if len(crates) == 1:
            return f"{relative}/{crates[0].name}/"
    return f"{relative}/"
