"""Generate and apply Dockle's framework-neutral theme."""

from __future__ import annotations

import json
import os
import re
import shutil
from html import escape
from html.parser import HTMLParser
from importlib.metadata import PackageNotFoundError, version
from pathlib import Path

from dockle import __version__
from dockle.config import DockleConfig, TargetConfig, ThemeConfig
from dockle.markdown import render_markdown

_HEAD_END = re.compile(r"</head\s*>", re.IGNORECASE)
_HTML_START = re.compile(r"<html(?P<attributes>\s[^>]*)?>", re.IGNORECASE)
_BODY_START = re.compile(r"<body(?P<attributes>\s[^>]*)?>", re.IGNORECASE)
_BODY_END = re.compile(r"</body\s*>", re.IGNORECASE)
_JSDOC_HOME_TITLE = re.compile(
    r'<h1\s+class=["\']page-title["\']>\s*Home\s*</h1>',
    re.IGNORECASE,
)
_JSDOC_GENERATOR_FOOTER = re.compile(
    r"<footer\b(?![^>]*data-dockle-built-with)[^>]*>\s*"
    r"Documentation generated by\s*<a[^>]*>\s*JSDoc\s+[^<]+</a>\s*"
    r"</footer>",
    re.IGNORECASE | re.DOTALL,
)
_DOXYGEN_GENERATOR_ITEM = re.compile(
    r'<li\s+class=["\']footer["\'][^>]*>\s*Generated by\s+.*?</li>',
    re.IGNORECASE | re.DOTALL,
)
_DOCKLE_FOOTER = re.compile(
    r"<footer\b(?=[^>]*data-dockle-built-with)[^>]*>.*?</footer>",
    re.IGNORECASE | re.DOTALL,
)
_TARGET_CARDS = re.compile(
    r'<div\s+data-dockle-target-cards(?:=["\'][^"\']*["\'])?[^>]*>'
    r".*?</div>",
    re.IGNORECASE | re.DOTALL,
)
_FIRST_H1_END = re.compile(r"</h1\s*>", re.IGNORECASE)
_DOCKLE_URL = "https://github.com/LizardByte/dockle"
_FRAMEWORKS = {
    "doxygen": ("Doxygen", "https://www.doxygen.nl/"),
    "jsdoc": ("JSDoc", "https://jsdoc.app/"),
    "mkdocs": ("MkDocs", "https://www.mkdocs.org/"),
    "rustdoc": ("rustdoc", "https://doc.rust-lang.org/rustdoc/"),
    "sphinx": ("Sphinx", "https://www.sphinx-doc.org/"),
}
_FRAMEWORK_VERSION_PATTERNS = {
    "doxygen": re.compile(
        r'<meta\s+name=["\']generator["\']\s+content=["\']Doxygen\s+([^"\']+)',
        re.IGNORECASE,
    ),
    "jsdoc": re.compile(
        r">\s*JSDoc\s+([^<]+)</a>",
        re.IGNORECASE,
    ),
    "rustdoc": re.compile(
        r'data-channel=["\']([^"\']+)',
        re.IGNORECASE,
    ),
}
_FRAMEWORK_DISTRIBUTIONS = {"mkdocs": "mkdocs", "sphinx": "Sphinx"}


class ThemeError(RuntimeError):
    """Raised when generated HTML cannot be themed safely."""


class _SearchDocumentParser(HTMLParser):
    """Collect useful searchable text from one generated HTML page."""

    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.title: list[str] = []
        self.text: list[str] = []
        self._in_title = False
        self._ignored = 0

    def handle_starttag(
        self,
        tag: str,
        attrs: list[tuple[str, str | None]],
    ) -> None:
        del attrs
        if tag in {"script", "style", "svg"}:
            self._ignored += 1
        if tag == "title":
            self._in_title = True

    def handle_endtag(self, tag: str) -> None:
        if tag == "title":
            self._in_title = False
        if tag in {"script", "style", "svg"} and self._ignored:
            self._ignored -= 1

    def handle_data(self, data: str) -> None:
        if self._ignored:
            return
        cleaned = " ".join(data.split())
        if not cleaned:
            return
        self.text.append(cleaned)
        if self._in_title:
            self.title.append(cleaned)


def _theme_asset(name: str) -> Path:
    return (
        Path(__file__)
        .with_name("sphinx")
        .joinpath("themes", "dockle", "static", name)
    )


def render_theme(theme: ThemeConfig) -> str:
    """Combine the base stylesheet with configured design tokens."""

    base = _theme_asset("dockle.css").read_text(encoding="utf-8")
    tokens = f"""/* Generated from dockle.toml. */
:root,
:root[data-color-scheme="light"] {{
  --dockle-primary: {theme.primary};
  --dockle-content: {theme.content};
  --dockle-background: {theme.light_background};
  --dockle-font: {theme.font};
  --dockle-code-font: {theme.code_font};
}}

:root[data-color-scheme="dark"] {{
  --dockle-content: #e5e7eb;
  --dockle-background: {theme.dark_background};
}}

@media (prefers-color-scheme: dark) {{
  :root:not([data-color-scheme]) {{
    --dockle-content: #e5e7eb;
    --dockle-background: {theme.dark_background};
  }}
}}
"""
    return f"{tokens}\n{base}"


def apply_theme(
    output: Path,
    framework: str,
    stylesheet: str,
    *,
    portal: Path | None = None,
    project_name: str = "",
    project_version: str = "",
    target_title: str = "",
    logo: Path | None = None,
) -> int:
    """Inject shared assets, navigation, branding, and client search."""

    html_files = sorted(output.rglob("*.html"))
    if not html_files:
        raise ThemeError(
            f"{framework} did not generate any HTML files in {output}"
        )

    asset_dir = output / "_dockle"
    asset_dir.mkdir(parents=True, exist_ok=True)
    (asset_dir / "dockle.css").write_text(stylesheet, encoding="utf-8")
    shutil.copyfile(
        _theme_asset("lucide.min.js"), asset_dir / "lucide.min.js"
    )
    shutil.copyfile(_theme_asset("dockle.js"), asset_dir / "dockle.js")
    logo_asset = _copy_logo(logo, asset_dir)
    search_documents = _build_search_documents(html_files, output)
    (asset_dir / "search.json").write_text(
        json.dumps({"docs": search_documents}, ensure_ascii=False),
        encoding="utf-8",
    )

    native_theme = framework in {"sphinx", "doxygen", "mkdocs"}
    framework_version = _framework_version(framework, html_files)
    footer = _built_with_footer(framework, framework_version)
    themed = 0
    for html_file in html_files:
        document = html_file.read_text(encoding="utf-8")
        changed = False
        if framework == "jsdoc" and html_file == output / "index.html":
            document, replacements = _JSDOC_HOME_TITLE.subn(
                "",
                document,
                count=1,
            )
            changed = replacements > 0
        if framework == "jsdoc":
            document, replacements = _JSDOC_GENERATOR_FOOTER.subn(
                "",
                document,
            )
            changed = changed or replacements > 0
        if framework == "doxygen":
            document, replacements = _DOXYGEN_GENERATOR_ITEM.subn(
                "",
                document,
            )
            changed = changed or replacements > 0

        if not native_theme and "data-dockle-theme" not in document:
            relative_css = _relative(asset_dir / "dockle.css", html_file)
            link = (
                f'<link rel="stylesheet" href="{relative_css}" '
                f'data-dockle-theme="{framework}">\n'
            )
            document = _insert_before_head_end(document, link, html_file)
            changed = True

        if "lucide.min.js" not in document:
            relative_lucide = _relative(
                asset_dir / "lucide.min.js", html_file
            )
            script = (
                f'<script defer src="{relative_lucide}" '
                "data-dockle-lucide></script>\n"
            )
            document = _insert_before_head_end(document, script, html_file)
            changed = True

        if "dockle.js" not in document:
            relative_script = _relative(asset_dir / "dockle.js", html_file)
            script = (
                f'<script defer src="{relative_script}" '
                "data-dockle-script></script>\n"
            )
            document = _insert_before_head_end(document, script, html_file)
            changed = True

        if "data-dockle-framework" not in document:
            html_start = _HTML_START.search(document)
            if html_start is None:
                raise ThemeError(
                    f"generated HTML has no root html element: {html_file}"
                )
            attributes = html_start.group("attributes") or ""
            themed_root = (
                f'<html data-dockle-framework="{framework}"{attributes}>'
            )
            document = (
                f"{document[:html_start.start()]}{themed_root}"
                f"{document[html_start.end():]}"
            )
            changed = True

        decorations = _page_decorations(
            html_file=html_file,
            output=output,
            portal=portal,
            framework=framework,
            project_name=project_name,
            project_version=project_version,
            target_title=target_title,
            logo_asset=logo_asset,
            include_theme_toggle=(
                "data-dockle-theme-toggle" not in document
            ),
        )
        if "data-dockle-universal-search" not in document:
            document = _insert_after_body(document, decorations, html_file)
            changed = True

        if "data-dockle-built-with" in document:
            updated_document, replacements = _DOCKLE_FOOTER.subn(
                footer,
                document,
                count=1,
            )
            if replacements and updated_document != document:
                document = updated_document
                changed = True
        else:
            document = _insert_before_body_end(
                document,
                footer,
                html_file,
            )
            changed = True

        if changed:
            html_file.write_text(document, encoding="utf-8")
            themed += 1
    return themed


def _insert_before_head_end(
    document: str,
    markup: str,
    html_file: Path,
) -> str:
    match = _HEAD_END.search(document)
    if match is None:
        raise ThemeError(
            f"generated HTML has no closing head element: {html_file}"
        )
    return f"{document[:match.start()]}{markup}{document[match.start():]}"


def _insert_after_body(
    document: str,
    markup: str,
    html_file: Path,
) -> str:
    match = _BODY_START.search(document)
    if match is None:
        raise ThemeError(f"generated HTML has no body element: {html_file}")
    return f"{document[:match.end()]}{markup}{document[match.end():]}"


def _insert_before_body_end(
    document: str,
    markup: str,
    html_file: Path,
) -> str:
    match = _BODY_END.search(document)
    if match is None:
        raise ThemeError(f"generated HTML has no closing body element: {html_file}")
    return f"{document[:match.start()]}{markup}{document[match.start():]}"


def _relative(asset: Path, html_file: Path) -> str:
    return Path(os.path.relpath(asset, html_file.parent)).as_posix()


def _copy_logo(logo: Path | None, asset_dir: Path) -> Path | None:
    if logo is None:
        return None
    destination = asset_dir / f"logo{logo.suffix.lower()}"
    shutil.copyfile(logo, destination)
    return destination


def _build_search_documents(
    html_files: list[Path],
    output: Path,
) -> list[dict[str, str]]:
    documents: list[dict[str, str]] = []
    for html_file in html_files:
        parser = _SearchDocumentParser()
        parser.feed(html_file.read_text(encoding="utf-8"))
        text = " ".join(parser.text)
        title = " ".join(parser.title)
        if not title:
            title = html_file.stem.replace("-", " ").title()
        documents.append(
            {
                "location": html_file.relative_to(output).as_posix(),
                "title": title,
                "text": text[:4000],
            }
        )
    return documents


def _page_decorations(
    *,
    html_file: Path,
    output: Path,
    portal: Path | None,
    framework: str,
    project_name: str,
    project_version: str,
    target_title: str,
    logo_asset: Path | None,
    include_theme_toggle: bool,
) -> str:
    relative_index = _relative(
        output / "_dockle" / "search.json",
        html_file,
    )
    relative_root = _relative(output, html_file)
    logo_url = _relative(logo_asset, html_file) if logo_asset else ""
    search = f"""<div class="dockle-search dockle-universal-search"
       data-dockle-universal-search data-dockle-logo-url="{logo_url}"
       data-dockle-target-title="{escape(target_title)}">
    <i class="dockle-search-icon" data-lucide="search" aria-hidden="true"></i>
    <label class="visually-hidden" for="dockle-search-input">
      Search documentation
    </label>
    <input id="dockle-search-input" type="search"
           placeholder="Search documentation" autocomplete="off"
           data-dockle-search="{relative_index}"
           data-dockle-root="{relative_root}">
    <ul class="dockle-search-results"
        data-dockle-search-results="dockle-search-input"
        aria-live="polite" hidden></ul>
  </div>"""
    links = ""
    if portal is not None:
        relative_portal = _relative(portal / "index.html", html_file)
        links += (
            f'<a class="dockle-home" href="{relative_portal}" '
            'data-dockle-home><i data-lucide="arrow-left" '
            'aria-hidden="true"></i>All docs</a>'
        )
    if (
        portal is not None
        and project_name
        and framework in {"doxygen", "jsdoc", "rustdoc"}
    ):
        relative_portal = _relative(portal / "index.html", html_file)
        version = (
            f"<span>{escape(project_version)}</span>"
            if project_version
            else ""
        )
        links += (
            f'<a class="dockle-compat-brand" href="{relative_portal}" '
            f"data-dockle-brand><strong>{escape(project_name)}</strong>"
            f"{version}</a>"
        )
    toggle = ""
    if include_theme_toggle:
        toggle = (
            '<button type="button" class="dockle-theme-toggle" '
            'data-dockle-theme-toggle aria-label="Color scheme: auto">'
            '<i data-lucide="monitor" aria-hidden="true"></i></button>'
        )
    return f'{links}<div class="dockle-toolbar">{search}{toggle}</div>'


def _framework_version(framework: str, html_files: list[Path]) -> str:
    pattern = _FRAMEWORK_VERSION_PATTERNS.get(framework)
    if pattern is not None:
        for html_file in html_files:
            match = pattern.search(html_file.read_text(encoding="utf-8"))
            if match is not None:
                return match.group(1).strip()
    distribution = _FRAMEWORK_DISTRIBUTIONS.get(framework)
    if distribution is None:
        return ""
    try:
        return version(distribution)
    except PackageNotFoundError:
        return ""


def _built_with_footer(framework: str = "", framework_version: str = "") -> str:
    framework_name, framework_url = _FRAMEWORKS.get(
        framework,
        (framework, ""),
    )
    framework_attribution = ""
    if framework_name:
        label = escape(framework_name)
        if framework_version:
            label += f" {escape(framework_version)}"
        if framework_url:
            label = (
                f'<a href="{framework_url}">{label}'
                '<i data-lucide="external-link" aria-hidden="true"></i></a>'
            )
        framework_attribution = f" with {label}"
    return (
        '<footer class="dockle-footer dockle-built-with" '
        'data-dockle-built-with>'
        f'Generated by <a href="{_DOCKLE_URL}">Dockle {__version__}'
        '<i data-lucide="external-link" aria-hidden="true"></i>'
        f'</a>{framework_attribution}.</footer>'
    )


def write_portal(
    config: DockleConfig,
    targets: tuple[TargetConfig, ...],
    stylesheet: str,
) -> Path:
    """Write the root project documentation and comparison cards."""

    output = config.build.output
    output.mkdir(parents=True, exist_ok=True)
    home_target = next((target for target in config.targets if target.home), None)
    card_targets = (
        tuple(target for target in config.targets if not target.home)
        if home_target is not None
        else targets
    )
    cards = _portal_cards(card_targets, output)
    portal = output / "index.html"
    if home_target is not None and portal.is_file():
        document = portal.read_text(encoding="utf-8")
        cards_markup = (
            '<div data-dockle-target-cards class="dockle-portal-grid" '
            'aria-label="Documentation examples">\n'
            f"{cards}\n"
            "</div>"
        )
        document, replacements = _TARGET_CARDS.subn(
            cards_markup, document, count=1
        )
        if not replacements:
            heading = _FIRST_H1_END.search(document)
            if heading is None:
                raise ThemeError(
                    f"home target has no heading for comparison cards: {portal}"
                )
            document = (
                f"{document[:heading.end()]}\n{cards_markup}"
                f"{document[heading.end():]}"
            )
        portal.write_text(document, encoding="utf-8")
        return portal

    asset_dir = output / "_dockle"
    asset_dir.mkdir(parents=True, exist_ok=True)
    (asset_dir / "dockle.css").write_text(stylesheet, encoding="utf-8")
    shutil.copyfile(
        _theme_asset("lucide.min.js"), asset_dir / "lucide.min.js"
    )
    shutil.copyfile(_theme_asset("dockle.js"), asset_dir / "dockle.js")
    logo_asset = _copy_logo(config.project.logo, asset_dir)

    version = (
        f" <span>{escape(config.project.version)}</span>"
        if config.project.version
        else ""
    )
    repository = ""
    if config.project.repository:
        repository = (
            '    <p class="dockle-portal-repository">'
            f'<a href="{escape(config.project.repository)}">'
            'Source repository<i data-lucide="external-link" '
            'aria-hidden="true"></i></a></p>\n'
        )
    logo = ""
    if logo_asset is not None:
        logo = (
            f'      <img class="dockle-portal-logo" '
            f'src="_dockle/{escape(logo_asset.name)}" alt="">\n'
        )
    project_docs = ""
    if config.project.home is not None:
        source = config.project.home.read_text(encoding="utf-8")
        project_docs = (
            '    <article class="dockle-portal-docs">\n'
            f"{render_markdown(source)}\n"
            "    </article>\n"
        )

    document = f"""<!doctype html>
<html lang="en" data-dockle-framework="portal">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="{escape(config.project.description)}">
  <title>{escape(config.project.name)} documentation</title>
  <link rel="stylesheet" href="_dockle/dockle.css" data-dockle-theme="portal">
  <script defer src="_dockle/lucide.min.js" data-dockle-lucide></script>
  <script defer src="_dockle/dockle.js" data-dockle-script></script>
</head>
<body class="dockle-portal">
  <main>
    <header>
{logo}      <div>
        <p class="dockle-portal-kicker">Documentation</p>
        <h1>{escape(config.project.name)}{version}</h1>
        <p>{escape(config.project.description)}</p>
      </div>
    </header>
    <section class="dockle-portal-grid" aria-label="Documentation examples">
{cards}
    </section>
{project_docs}{repository}  </main>
  <footer class="dockle-footer dockle-built-with dockle-portal-built-with"
          data-dockle-built-with>
    Generated by <a href="{_DOCKLE_URL}">Dockle {__version__}<i
      data-lucide="external-link" aria-hidden="true"></i></a>.
  </footer>
  <button type="button" class="dockle-theme-toggle"
          data-dockle-theme-toggle aria-label="Color scheme: auto">
    <i data-lucide="monitor" aria-hidden="true"></i>
  </button>
</body>
</html>
"""
    portal.write_text(document, encoding="utf-8")
    return portal


def _portal_cards(
    targets: tuple[TargetConfig, ...], output: Path
) -> str:
    """Render the shared comparison cards for portal or Sphinx home pages."""

    cards: list[str] = []
    for target in targets:
        relative = _target_href(target, output)
        description = target.description or (
            f"Documentation generated with {target.framework}."
        )
        cards.append(
            f"""      <a class="dockle-portal-card" href="{escape(relative)}">
        <span class="dockle-portal-framework">{escape(target.framework)}</span>
        <strong>{escape(target.title)}</strong>
        <span>{escape(description)}</span>
      </a>"""
        )
    return "\n".join(cards)


def _target_href(target: TargetConfig, output: Path) -> str:
    relative = target.output.relative_to(output).as_posix()
    if target.framework == "rustdoc" and target.output.is_dir():
        crates = sorted(
            path
            for path in target.output.iterdir()
            if path.is_dir() and (path / "index.html").is_file()
        )
        if len(crates) == 1:
            return f"{relative}/{crates[0].name}/"
    return f"{relative}/"
